In [325]:
In [1]: import numpy as np

In [2]: import pandas as pd

In [326]:
In [3]: from pandas import Series, DataFrame

In [327]:
# 5.1 INTRODUCTION TO PANDAS DATA STRUCTURES

In [328]:
#SERIES

In [329]:
obj = pd.Series([4, 7, -5, 3])

In [330]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [331]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [332]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [333]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [334]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [335]:
obj2["a"]

np.int64(-5)

In [336]:
obj2["d"]=6

In [337]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [338]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [339]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [340]:
import numpy as np

In [341]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [342]:
"b" in obj2

True

In [343]:
"e" in obj2

False

In [344]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [345]:
obj3 = pd.Series(sdata)

In [346]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [347]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [348]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [349]:
obj4 = pd.Series(sdata, index=states)

In [350]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [351]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [352]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [353]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [354]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [355]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [356]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [357]:
obj4.name = "population"

In [358]:
obj4.index.name = "state"

In [359]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [360]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [361]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [362]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [363]:
#DATAFRAME

In [364]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000,2001,2002,2001,2002,2003],
        "pop": [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [365]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [366]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [367]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [368]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [369]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [370]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [371]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [372]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [373]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [374]:
frame2["dbt"] = 16.5
frame2

year   state  pop debt   dbt
0  2000    Ohio  1.5  NaN  16.5
1  2001    Ohio  1.7  NaN  16.5
2  2002    Ohio  3.6  NaN  16.5
3  2001  Nevada  2.4  NaN  16.5
4  2002  Nevada  2.9  NaN  16.5
5  2003  Nevada  3.2  NaN  16.5

In [375]:
frame2["debt"] = np.arange(6.)
frame2

year   state  pop  debt   dbt
0  2000    Ohio  1.5   0.0  16.5
1  2001    Ohio  1.7   1.0  16.5
2  2002    Ohio  3.6   2.0  16.5
3  2001  Nevada  2.4   3.0  16.5
4  2002  Nevada  2.9   4.0  16.5
5  2003  Nevada  3.2   5.0  16.5

In [376]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2,4,5])
frame2["debt"] = val
frame2

year   state  pop  debt   dbt
0  2000    Ohio  1.5   NaN  16.5
1  2001    Ohio  1.7   NaN  16.5
2  2002    Ohio  3.6  -1.2  16.5
3  2001  Nevada  2.4   NaN  16.5
4  2002  Nevada  2.9  -1.5  16.5
5  2003  Nevada  3.2  -1.7  16.5

In [377]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [378]:
frame2

year   state  pop  debt   dbt  eastern
0  2000    Ohio  1.5   NaN  16.5     True
1  2001    Ohio  1.7   NaN  16.5     True
2  2002    Ohio  3.6  -1.2  16.5     True
3  2001  Nevada  2.4   NaN  16.5    False
4  2002  Nevada  2.9  -1.5  16.5    False
5  2003  Nevada  3.2  -1.7  16.5    False

In [379]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'dbt'], dtype='object')

In [380]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}

In [381]:
frame3 = pd.DataFrame(populations)

In [382]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [383]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [384]:
pd.DataFrame(populations, index=[2001,2002,2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [385]:
pdata = {"Ohio": frame3["Ohio"][:-1],"Nevada": frame3["Nevada"][:2]}

In [386]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [387]:
frame3.index.name = "year"

In [388]:
frame3.columns.name = "state"

In [389]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [390]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [391]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan, 16.5],
       [2001, 'Ohio', 1.7, nan, 16.5],
       [2002, 'Ohio', 3.6, -1.2, 16.5],
       [2001, 'Nevada', 2.4, nan, 16.5],
       [2002, 'Nevada', 2.9, -1.5, 16.5],
       [2003, 'Nevada', 3.2, -1.7, 16.5]], dtype=object)

In [ ]:
#OBJECTS

In [393]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [394]:
index = obj.index

In [395]:
index

Index(['a', 'b', 'c'], dtype='object')

In [397]:
index[1:]

Index(['b', 'c'], dtype='object')

In [398]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [399]:
labels = pd.Index(np.arange(3))

In [400]:
labels

Index([0, 1, 2], dtype='int64')

In [403]:
obj2 = pd.Series([1.5, -2.5,0], index=labels)

In [404]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [405]:
obj2.index is labels

True

In [406]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [407]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [408]:
"Ohio" in frame3.columns

True

In [409]:
2003 in frame3.index

False

In [410]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
#5.2 ESSENTIAL FUNCTIONALITY

In [ ]:
#REINDEXING

In [446]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
index=["d", "b", "a", "c"])

In [447]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [448]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [449]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [450]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [451]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [452]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [453]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
index=["a", "c", "d"],
columns=["Ohio", "Texas", "California"])

In [454]:
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [455]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [456]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [457]:
states = ["Texas", "Utah", "California"]

In [458]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [459]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [460]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [ ]:
#Dropping Entries from an Axis

In [461]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [462]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [463]:
new_obj = obj.drop("c")

In [464]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [465]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [466]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"],columns=["one", "two", "three", "four"])

In [467]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [468]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [469]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [470]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [471]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
#Indexing, Selection, and Filtering

In [472]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [473]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [477]:
obj["b"]

np.float64(1.0)

In [495]:
obj.iloc[1]

np.float64(1.0)

In [480]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [481]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [496]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [484]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [485]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [486]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [487]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [488]:
obj1

2    1
0    2
1    3
dtype: int64

In [489]:
obj2

a    1
b    2
c    3
dtype: int64

In [503]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [504]:
obj2[[0, 1, 2]]

/var/folders/wb/8wsxvd891919zfypc_lw4yqr0000gp/T/ipykernel_7014/2599987575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]


a    1
b    2
c    3
dtype: int64

In [505]:
obj2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [500]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [501]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [506]:
 obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [507]:
obj2.loc["b":"c"] = 5

In [508]:
obj2

a    1
b    5
c    5
dtype: int64

In [509]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"],columns=["one", "two", "three", "four"])

In [510]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [511]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [513]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [514]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [515]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [516]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [517]:
data[data < 5] = 0

In [518]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
#Selection on DataFrame with loc and iloc

In [519]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [520]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [521]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [522]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [523]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [524]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [525]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [526]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [527]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [528]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [529]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
#Integer indexing pitfalls


In [530]:
ser = pd.Series(np.arange(3.))

In [531]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [532]:
ser[-1]

KeyError: -1

In [533]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [534]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [535]:
ser2[-1] - #update to ser2.iloc[-1]

/var/folders/wb/8wsxvd891919zfypc_lw4yqr0000gp/T/ipykernel_7014/811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [696]:
ser2.iloc[-1]

np.float64(2.0)

In [536]:
ser.iloc[-1]

np.float64(2.0)

In [537]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [ ]:
#Pitfalls with chained indexing


In [538]:
data.loc[:, "one"] = 1

In [539]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [540]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [541]:
data.iloc[2] = 5

In [542]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [543]:
data.loc[data["four"]>5] =3

In [544]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [545]:
data.loc[data.three ==5, "three"] = 6

In [546]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [ ]:
#Arithmetic and Data Alignment


In [547]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [548]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [549]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [550]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [551]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [552]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])

In [553]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [554]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [555]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [556]:
df1 +df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [557]:
df1 = pd.DataFrame({"A": [1, 2]})

In [558]:
df2 = pd.DataFrame({"B": [3, 4]})

In [559]:
df1

A
0  1
1  2

In [560]:
df2

B
0  3
1  4

In [561]:
df1 +df2

A   B
0 NaN NaN
1 NaN NaN

In [ ]:
#Arithmetic methods with fill values


In [562]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list("abcd"))

In [563]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list("abcde"))

In [564]:
df2.loc[1, "b"] = np.nan

In [565]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [566]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [567]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [568]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [569]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [570]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [571]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [ ]:
#Operations between DataFrame and Series


In [572]:
arr = np.arange(12.).reshape((3, 4))

In [573]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [574]:
arr[0]

array([0., 1., 2., 3.])

In [575]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [576]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [577]:
series = frame.iloc[0]

In [578]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [579]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [580]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [581]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [582]:
series2

b    0
e    1
f    2
dtype: int64

In [583]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [584]:
series3 = frame["d"]

In [585]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [586]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [587]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
#Function Application and Mapping

In [594]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [599]:
frame

b         d         e
Utah    1.098101  0.334313  1.071335
Ohio   -0.070427  0.165643  0.171348
Texas   0.871183  0.430039 -0.191519
Oregon -2.256463 -1.288807  1.931670

In [600]:
np.abs(frame)

b         d         e
Utah    1.098101  0.334313  1.071335
Ohio    0.070427  0.165643  0.171348
Texas   0.871183  0.430039  0.191519
Oregon  2.256463  1.288807  1.931670

In [597]:
def f1(x): return x.max() - x.min()

In [598]:
frame.apply(f1)

b    3.354563
d    1.718846
e    2.123189
dtype: float64

In [601]:
def f1(x):return x.max() - x.min()

In [602]:
frame.apply(f1)

b    3.354563
d    1.718846
e    2.123189
dtype: float64

In [603]:
frame.apply(f1, axis = "columns")

Utah      0.763788
Ohio      0.241775
Texas     1.062702
Oregon    4.188133
dtype: float64

In [604]:
def f2(x):return pd.Series([x.min(), x.max()], index=["min", "max"])

In [605]:
frame.apply(f2)

b         d         e
min -2.256463 -1.288807 -0.191519
max  1.098101  0.430039  1.931670

In [608]:
def my_format(x):return f"{x:.2f}"

In [609]:
frame.applymap(my_format) #old code - updated to frame = frame.apply(lambda col: col.map(my_format))

/var/folders/wb/8wsxvd891919zfypc_lw4yqr0000gp/T/ipykernel_7014/1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


b      d      e
Utah     1.10   0.33   1.07
Ohio    -0.07   0.17   0.17
Texas    0.87   0.43  -0.19
Oregon  -2.26  -1.29   1.93

In [695]:
frame = frame.apply(lambda col: col.map(my_format))

In [610]:
frame["e"].map(my_format)

Utah       1.07
Ohio       0.17
Texas     -0.19
Oregon     1.93
Name: e, dtype: object

In [ ]:
#Sorting and Ranking

In [611]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [612]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [613]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [614]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=["three", "one"],columns=["d", "a", "b", "c"])

In [615]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [616]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [617]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [618]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [619]:
obj = pd.Series([4, 7, -3, 2])

In [620]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [621]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [622]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [623]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [624]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [625]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [626]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [627]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [628]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [629]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [631]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [632]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [633]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],"c": [-2, 5, 8, -2.5]})

In [634]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [635]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [636]:
#Axis Indexes with Duplicate Labels

In [637]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [638]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [639]:
obj.index.is_unique

False

In [641]:
obj["a"]

a    0
a    1
dtype: int64

In [642]:
obj["c"]

np.int64(4)

In [643]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),index=["a", "a", "b", "b", "c"])

In [644]:
df

0         1         2
a -0.953653  1.301709 -1.296325
a  0.422274 -2.011462 -0.364760
b  0.144862  0.738877 -0.265906
b  0.888245 -0.630351  0.046522
c -0.072638  0.964841 -0.907153

In [645]:
df.loc["b"]

0         1         2
b  0.144862  0.738877 -0.265906
b  0.888245 -0.630351  0.046522

In [646]:
df.loc["c"]

0   -0.072638
1    0.964841
2   -0.907153
Name: c, dtype: float64

In [647]:
#5.3 Summarizing and Computing Descriptive Statistics

In [648]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=["a", "b", "c", "d"],columns=["one", "two"])

In [649]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [650]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [651]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [652]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [653]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [654]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [655]:
df.idxmax()

one    b
two    d
dtype: object

In [656]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [657]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [658]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [659]:
#Correlation and Covariance - Need data for example_It will not run

In [664]:
price = pd.read_pickle

In [665]:
volume = pd.read_pickle

In [666]:
returns = price.pct_change()

AttributeError: 'function' object has no attribute 'pct_change'

In [ ]:
#Unique Values, Value Counts, and Membership


In [667]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [668]:
uniques = obj.unique()

In [670]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [671]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [672]:
#pd.value_counts(obj.to_numpy(), sort=False)

/var/folders/wb/8wsxvd891919zfypc_lw4yqr0000gp/T/ipykernel_7014/164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [673]:
pd.Series(obj).value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [674]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [675]:
mask = obj.isin(["b", "c"])

In [680]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [681]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [682]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [683]:
unique_vals = pd.Series(["c", "b", "a"])

In [684]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [685]:
indices

array([0, 2, 1, 1, 0, 2])

In [686]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],"Qu2": [2, 3, 1, 2, 3],"Qu3": [1, 5, 2, 4, 4]})

In [687]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [688]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [689]:
result = data.apply(pd.value_counts).fillna(0)

/var/folders/wb/8wsxvd891919zfypc_lw4yqr0000gp/T/ipykernel_7014/2451317050.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


In [690]:
result = data.apply(lambda col: pd.Series(col).value_counts()).fillna(0)

In [691]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [692]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})

In [693]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [694]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64